---
# tasks file for deploy_jenkins
# - hosts: tag_Name_devtools
#   vars:
#     ansible_ssh_private_key_file: "/Users/admin/awskey/testkp.pem"
#     ansible_ssh_user: "ubuntu"
    
#   become: yes
#   tasks:
    - name: Ensure dependencies are installed.
      apt:
        name:
        - curl
        - apt-transport-https
        - openjdk-8-jdk
        state: present

    - name: Add Jenkins apt repository key.
      apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins.io.key"
        state: present

    - name: Add Jenkins apt repository.
      apt_repository:
        repo: "deb http://pkg.jenkins-ci.org/debian binary/"
        state: present
        update_cache: true

    - name: install jenkins
      apt:
        update_cache: yes
        name: jenkins
        state: present

    - name: Create initialization scripts directory
      file: path={{ jenkins_home }}/init.groovy.d
        state=directory
        owner=jenkins
        group=jenkins
        mode=0775    
        
    - name: Add initialization script to setup basic security
      template: src=security.groovy.j2
            dest={{ jenkins_home }}/init.groovy.d/security.groovy
            owner=jenkins
            group=jenkins
            mode=0775   
    - name: Jenkins - configure | Turn off Jenkins setup wizard
      lineinfile: 
          dest=/etc/default/jenkins 
          regexp='^JENKINS_JAVA_OPTIONS=' 
          line='JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
      notify: restart jenkins
    

    - name: Start the server
      service:
        name: jenkins
        state: started

    - name: Wait for Jenkins to start up
      uri:
        url: http://localhost:8080
        status_code: 200
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
        timeout: 5
        force_basic_auth: yes
        register: jenkins_service_status
        retries: 10
        delay: 5
        until: >
          'status' in jenkins_service_status and
          jenkins_service_status['status'] == 200
    
    # - name: Check Jenkins status
    #   debug:
    #    msg: "Jenkins status: {{ jenkins_service_status['status'] }}"

    - name: install plugin
      jenkins_plugin:
        name: "{{ item }}"
        state: latest
        url_username: "{{jenkins_admin_username}}"
        url_password: "{{jenkins_admin_password}}"
        url: http://localhost:8080
      with_items: "build-pipeline-plugin"

    - name: ReStart the server
      service:
        name: jenkins
        state: restarted
