---
# vars file for deploy_jenkins
jenkins_home: "/var/lib/jenkins"
jenkins_admin_username: jenkins
jenkins_admin_password: jenkins
ansible_ssh_private_key_file: "/Users/admin/awskey/testkp.pem"
ansible_ssh_user: "ubuntu"