---
#tasks:
 - name: check docker is installed
   apt: 
     name: 
      - docker.io
      - python-pip
     state: present

 - name: install pip depends
   pip:
    name: docker

 - name: run docker container
   docker_container:  
     name: springboot
     image: "denhermesss/graduate:{{ BUILD_NUMBER }}"
     published_ports: "{{PORT_NUMBER}}:{{PORT_NUMBER}}"
     state: started