pipeline {

    agent any
    environment {
        finalname = "spring-boot-smoke-test-web-ui-${env.BUILD_NUMBER}"
    }
    tools {
        maven "LOCALMAVEN"
        jdk 'javalocal'
    }
     
    stages {
        stage(CHECKOUT) {
            //git repo checkout
            steps {
                git 'https://github.com/Hermesss/spring-boot.git'
            }
        }
        stage(BUILD) {
            steps {
                sh "mvn clean  install -f /var/lib/jenkins/jobs/graduate/workspace/spring-boot-smoke-tests/spring-boot-smoke-test-web-ui/pom.xml -Dmaven.test.skip=true -Dmaven.test.failure.ignore=true"                 
                
                }


        }
        
        
        stage(UPLOAD) {
            steps {
                rtServer (
                    id: "Artifactory",
                    url: "http://artifactory:8081/artifactory",
                    // If you're using username and password:
                    username: "jenkins",
                    password: "jenkins88"
                )      
                rtUpload (
                    serverId: "Artifactory",
                    spec:
                        """{
                        "files": [
                            {
                            "pattern": "/var/lib/jenkins/jobs/graduate/workspace/spring-boot-smoke-tests/spring-boot-smoke-test-web-ui/target/*.jar",
                            "target": "libs-snapshot-local/org/springframework/boot/spring-boot-smoke-test-web-ui/2.2.0.BUILD-SNAPSHOT/${env.finalname}.jar"
                            }
                        ]
                        }"""
                ) 
                rtPublishBuildInfo (
                    serverId: "Artifactory"
                ) 

            }
        
        }
        stage(CI_DEPLOY) {
            steps {
                dir ('Deployment') {
                    echo "====++++Deploying to CI++++===="
                    sh "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook  /var/lib/jenkins/jobs/graduate/workspace/Deployment/deploy_app.yml -e 'BUILD_NUMBER=${env.BUILD_NUMBER} ENV=ci' -vv"
                }
            }

        }
        stage("deploy to QA") {
            input {
                message "Should we deploy to QA env?"
            }
            steps {
                echo "====++++Deploying to QA++++===="
                sh "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i /var/lib/jenkins/jobs/graduate/workspace/Deployment/roles/devtools.ini /var/lib/jenkins/workspace/graduate/Deployment/roles/deploy.yml -e 'BUILD_NUMBER=${env.BUILD_NUMBER} ENV=qa'"
            }
        }
    }
    
}