---
#- hosts: tag_Name_devtools
#  vars:
#    ansible_ssh_private_key_file: "~/awskey/testkp.pem"
#    ansible_ssh_user: "ubuntu"
# become: yes
# roles: 
#   - deploy_devtools

- hosts: tag_Name_artifactory
  vars:
    ansible_ssh_private_key_file: "~/awskey/testkp.pem"
    ansible_ssh_user: "ubuntu"
  become: yes
  roles:
   - bastiaanvanassche.s3fs-fuse
   - deploy_artifactory
   