---
# tasks file for deploy_artifactory
- name: create the file to be used for swap
  command: fallocate -l 1G /mnt/1GB.swap

- name: format the file for swap
  command: mkswap /mnt/1GB.swap

- name: change swap file permissions
  file: path=/mnt/1GB.swap owner=root group=root mode=0600

- name: add the file to the system as a swap file
  command: swapon /mnt/1GB.swap

- name: write swap entry in fstab
  mount: name=none src=/mnt/1GB.swap fstype=swap opts=sw passno=0 dump=0 state=present

- name: install Docker    
  apt:
      update_cache: yes
      name: docker.io
      state: present
  
- name: run Artifactory-Docker container
  command: "docker run --name artifactory -d -p 8081:8081 -v /mnt/s3/jfrog/artifactory:/var/opt/jfrog/artifactory  docker.bintray.io/jfrog/artifactory-oss:latest"