---
# tasks file for deploy_artifactory
- name: Ensure dependencies are installed.
  apt:
    name:
      - tar
      - zip
    state: present

- name: create the file to be used for swap
  command: fallocate -l 4G /mnt/4GB.swap
  

- name: format the file for swap
  command: mkswap /mnt/4GB.swap

- name: change swap file permissions
  file: path=/mnt/4GB.swap owner=root group=root mode=0600

- name: add the file to the system as a swap file
  command: swapon /mnt/4GB.swap

- name: write swap entry in fstab
  mount: name=none src=/mnt/4GB.swap fstype=swap opts=sw passno=0 dump=0 state=present

- name: install Docker    
  apt:
      update_cache: yes
      name: docker.io
      state: present

- name: 'add users to docker group'
  user:
    name: 'ubuntu'
    groups: 'docker'
    append: 'yes'

- name: retrieve artifactory config from github
  get_url: 
     url=https://github.com/Hermesss/spring-boot/raw/master/Deployment/artifactory.zip 
     dest=/usr/src/artifactory.zip
     owner=root
     mode=0755

- name: extract zip of artifactory
  unarchive:
    src: /usr/src/artifactory.zip
    remote_src: yes
    dest: /usr/src
        
- name: change jfrog folder permissions
  command: 'chown -hR 1030:1030 /usr/src/jfrog'

- name: run Artifactory-Docker container
  command: "docker run --name artifactory -d -p 8081:8081 -v /usr/src/jfrog/artifactory:/var/opt/jfrog/artifactory -e EXTRA_JAVA_OPTIONS='-Xms512m -Xmx4G -Xss256k -XX:+UseG1GC'  docker.bintray.io/jfrog/artifactory-oss:latest"